encouragements = [
    "You're doing great! Keep going!",
    "Every problem you solve makes you stronger!",
    "Believe in yourself, you can do it!",
    "Mathematics is all about practice, keep practicing!",
    "You're making progress, even if it doesn't feel like it!",
    "Don't give up, you're closer than you think!",
    "Math is a journey, enjoy the process!",
    "You're capable of more than you think!",
    "Mistakes are opportunities to learn, embrace them!",
    "You're on the right track, keep going!",
    "Your effort today will pay off tomorrow!",
    "Mathematics is a language, and you're becoming fluent!",
    "You're building a strong foundation!",
    "Each problem solved is a step forward!",
    "Challenge yourself, that's where the growth happens!",
    "Keep calm and solve equations!",
    "Mathematics is beautiful, and so are you!",
    "Visualize your success, then make it happen!",
    "Mathematics is like a puzzle, piece by piece you'll solve it!",
    "You've got this!",
    "Don't stress over the process, enjoy the journey!",
    "You're not alone, many have faced this before and succeeded!",
    "Stay positive, you're closer to the solution than you think!",
    "Mathematics is a marathon, not a sprint. Keep pacing!",
    "You're building a powerful mind!",
    "Your determination will take you far!",
    "Mathematics is the music of reason, and you're its composer!",
    "The more you practice, the easier it gets!",
    "Success is the sum of small efforts repeated day in and day out!",
    "Mathematics is your playground, explore its wonders!",
    "You're not giving up, you're giving yourself a chance to succeed!",
    "You're turning challenges into opportunities!",
    "Mathematics is your superpower, embrace it!",
    "Your potential is limitless!",
    "You're becoming a problem-solving ninja!",
    "Every step forward is a victory!",
    "Mathematics is a journey of self-discovery!",
    "You're growing with every challenge you face!",
    "Focus on progress, not perfection!",
    "You're building a solid mathematical foundation!",
    "Mathematics is your canvas, paint your masterpiece!",
    "Don't let setbacks define you, let them refine you!",
    "You're in control of your success!",
    "Mathematics is your friend, not your foe!",
    "Your effort today will create a brighter tomorrow!",
    "You're not alone in this journey!",
    "Mathematics is a language, and you're becoming fluent!",
    "Stay curious, stay hungry for knowledge!",
    "You're developing problem-solving skills that will last a lifetime!",
    "You're planting seeds of success with every equation you solve!",
    "Mathematics is the key to unlocking endless possibilities!",
    "You're building resilience with every challenge you overcome!",
    "Your hard work will pay off!",
    "Mathematics is your playground, explore its wonders!",
    "You're not just learning math, you're mastering it!",
    "Embrace the struggle, it's shaping you into a stronger person!",
    "You're becoming a math wizard!",
    "Mathematics is your ally, not your enemy!",
    "You're on a journey to mathematical mastery!",
    "You're making progress, even if it's not always visible!",
    "Mathematics is a puzzle, and you're the solver!",
    "You're creating a brighter future with every equation you solve!",
    "Don't be afraid to ask for help when you need it!",
    "You're capable of amazing things!",
    "Mathematics is your passion, pursue it with all your heart!",
    "You're not just learning math, you're conquering it!",
    "You're laying the foundation for a successful future!",
    "Mathematics is your secret weapon!",
    "You're becoming a math aficionado!",
    "Every challenge you face is an opportunity for growth!",
    "Mathematics is a journey of self-discovery and growth!",
    "You're becoming a master problem solver!",
    "You're not just studying math, you're mastering it!",
    "Mathematics is your playground, explore its depths!",
    "You're building a solid mathematical foundation for success!",
    "You're not just solving problems, you're unlocking solutions!",
    "Mathematics is your passion, let it guide you to greatness!",
    "You're not just learning math, you're embracing it!",
    "Mathematics is a puzzle, and you're the missing piece!",
    "You're on the path to mathematical mastery!",
    "You're not just studying math, you're becoming a mathlete!",
    "Mathematics is your ally, not your adversary!",
    "You're not just solving equations, you're shaping your destiny!",
    "Mathematics is your superpower, use it to change the world!",
    "You're not just learning math, you're transforming yourself!",
    "Mathematics is your compass, guiding you to success!",
    "You're not just tackling problems, you're overcoming obstacles!",
    "Mathematics is your passion, let it ignite your potential!",
    "You're not just studying math, you're unleashing your genius!",
    "Mathematics is your playground, explore its infinite possibilities!",
    "You're not just solving equations, you're conquering challenges!",
    "Mathematics is your passion, pursue it relentlessly!",
    "You're not just studying math, you're mastering the universe!",
    "Mathematics is your weapon, wield it with confidence!",
    "You're not just learning math, you're reshaping the future!",
    "Mathematics is your path to greatness, walk it with pride!",
    "You're not just solving problems, you're making history!",
    "Mathematics is your calling, answer it with determination!",
    "You're not just studying math, you're becoming a legend!",
    "Mathematics is your destiny, embrace it with open arms!",
    "You're not just learning math, you're changing the world!",
    "Mathematics is your passion, let it fuel your ambition!",
    "You're not just studying math, you're defining the future!",
    "Mathematics is your gift, share it with the world!",
    "You're not just solving equations, you're unlocking miracles!",
    "Mathematics is your legacy, build it with pride!",
    "You're not just learning math, you're inspiring greatness!",
    "Mathematics is your purpose, fulfill it with passion!",
    "You're not just studying math, you're creating a masterpiece!",
    "Mathematics is your journey, embrace every step with joy!",
    "You're not just solving problems, you're shaping your destiny!",
    "Mathematics is your passion, let it guide you to success!",
    "You're not just studying math, you're mastering the universe!",
    "Mathematics is your playground, explore its infinite possibilities!",
    "You're not just solving equations, you're conquering challenges!",
    "Mathematics is your passion, pursue it relentlessly!",
    "You're not just studying math, you're unleashing your genius!",
    "Mathematics is your weapon, wield it with confidence!",
    "You're not just learning math, you're reshaping the future!",
    "Mathematics is your path to greatness, walk it with pride!",
    "You're not just solving problems, you're making history!",
    "Mathematics is your calling, answer it with determination!",
    "You're not just studying math, you're becoming a legend!",
    "Mathematics is your destiny, embrace it with open arms!",
    "You're not just learning math, you're changing the world!",
    "Mathematics is your passion, let it fuel your ambition!",
    "You're not just studying math, you're defining the future!",
    "Mathematics is your gift, share it with the world!",
    "You're not just solving equations, you're unlocking miracles!",
    "Mathematics is your legacy, build it with pride!",
    "You're not just learning math, you're inspiring greatness!",
    "Mathematics is your purpose, fulfill it with passion!",
    "You're not just studying math, you're creating a masterpiece!",
    "Mathematics is your journey, embrace every step with joy!"
]